using System;
using Xunit;

namespace Helpers.Cineworld.Models.Tests
{
	public class CinemaTypeTests
	{
		[Theory]
		[InlineData("Cineworld Aberdeen - Queens Links")]
		[InlineData("Cineworld Aberdeen - Union Square")]
		[InlineData("Cineworld Aldershot")]
		[InlineData("Cineworld Ashford")]
		[InlineData("Cineworld Ashton-under-Lyne")]
		[InlineData("Cineworld Basildon")]
		[InlineData("Cineworld Bedford")]
		[InlineData("Cineworld Birmingham - Broad Street")]
		[InlineData("Cineworld Birmingham - NEC")]
		[InlineData("Cineworld Boldon Tyne and Wear")]
		[InlineData("Cineworld Bolton")]
		[InlineData("Cineworld Bracknell")]
		[InlineData("Cineworld Bradford")]
		[InlineData("Cineworld Braintree")]
		[InlineData("Cineworld Brighton")]
		[InlineData("Cineworld Bristol")]
		[InlineData("Cineworld Broughton")]
		[InlineData("Cineworld Burton upon Trent")]
		[InlineData("Cineworld Bury St Edmunds")]
		[InlineData("Cineworld Cardiff")]
		[InlineData("Cineworld Castleford")]
		[InlineData("Cineworld Cheltenham")]
		[InlineData("Cineworld Chesterfield")]
		[InlineData("Cineworld Chichester")]
		[InlineData("Cineworld Crawley")]
		[InlineData("Cineworld Dalton Park")]
		[InlineData("Cineworld Didcot")]
		[InlineData("Cineworld Didsbury")]
		[InlineData("Cineworld Dover")]
		[InlineData("Cineworld Dundee")]
		[InlineData("Cineworld Eastbourne at The Beacon")]
		[InlineData("Cineworld Edinburgh")]
		[InlineData("Cineworld Ely")]
		[InlineData("Cineworld Falkirk")]
		[InlineData("Cineworld Glasgow - IMAX at GSC")]
		[InlineData("Cineworld Glasgow - Parkhead")]
		[InlineData("Cineworld Glasgow - Renfrew Street")]
		[InlineData("Cineworld Glasgow - Silverburn")]
		[InlineData("Cineworld Gloucester Quays")]
		[InlineData("Cineworld Harlow - Harvey Centre")]
		[InlineData("Cineworld Harlow - Queensgate")]
		[InlineData("Cineworld Haverhill")]
		[InlineData("Cineworld Hemel Hempstead")]
		[InlineData("Cineworld High Wycombe")]
		[InlineData("Cineworld Hinckley")]
		[InlineData("Cineworld Hull")]
		[InlineData("Cineworld Huntingdon")]
		[InlineData("Cineworld Ipswich")]
		[InlineData("Cineworld - Isle of Wight")]
		[InlineData("Cineworld Jersey")]
		[InlineData("Cineworld Leeds - White Rose")]
		[InlineData("Cineworld Leigh")]
		[InlineData("Cineworld Llandudno")]
		[InlineData("Cineworld London - Bexleyheath")]
		[InlineData("Cineworld London - Enfield")]
		[InlineData("Cineworld London - Feltham")]
		[InlineData("Cineworld London - Ilford")]
		[InlineData("Cineworld London - Leicester Square")]
		[InlineData("Cineworld London - South Ruislip")]
		[InlineData("Cineworld London - The O2 Greenwich")]
		[InlineData("Cineworld London - Wandsworth")]
		[InlineData("Cineworld London - Wembley")]
		[InlineData("Cineworld London - West India Quay")]
		[InlineData("Cineworld London - Wood Green")]
		[InlineData("Cineworld Loughborough")]
		[InlineData("Cineworld Luton")]
		[InlineData("Cineworld Middlesbrough")]
		[InlineData("Cineworld Milton Keynes")]
		[InlineData("Cineworld Newcastle upon Tyne")]
		[InlineData("Cineworld Newport - Friars Walk")]
		[InlineData("Cineworld Newport - Spytty Park")]
		[InlineData("Cineworld Northampton")]
		[InlineData("Cineworld Nottingham")]
		[InlineData("Cineworld Plymouth")]
		[InlineData("Cineworld Poole")]
		[InlineData("Cineworld Rochester")]
		[InlineData("Cineworld Rugby")]
		[InlineData("Cineworld Runcorn")]
		[InlineData("Cineworld Rushden Lakes")]
		[InlineData("Cineworld Sheffield")]
		[InlineData("Cineworld Shrewsbury")]
		[InlineData("Cineworld Solihull")]
		[InlineData("Cineworld Speke")]
		[InlineData("Cineworld St Helens")]
		[InlineData("Cineworld St Neots")]
		[InlineData("Cineworld Stevenage")]
		[InlineData("Cineworld Stoke-on-Trent")]
		[InlineData("Cineworld Swindon - Regent Circus")]
		[InlineData("Cineworld Swindon - Shaw Ridge")]
		[InlineData("Cineworld Telford")]
		[InlineData("Cineworld Wakefield")]
		[InlineData("Cineworld Warrington")]
		[InlineData("Cineworld Watford")]
		[InlineData("Cineworld Weston-super-Mare")]
		[InlineData("Cineworld Weymouth")]
		[InlineData("Cineworld Whiteley")]
		[InlineData("Cineworld Witney")]
		[InlineData("Cineworld Wolverhampton")]
		[InlineData("Cineworld Yate")]
		[InlineData("Cineworld Yeovil")]
		[InlineData("Cineworld York")]
		public void FixName(string name)
		{
			// Assert
			Assert.StartsWith("Cineworld ", name, StringComparison.InvariantCulture);

			// Act
			var cinema = new Generated.CinemaType { Name = name, };

			// Assert
			Assert.NotNull(cinema.Name);
			Assert.NotEmpty(cinema.Name);
			Assert.Equal(cinema.Name, cinema.Name.Trim(), StringComparer.InvariantCulture);
			Assert.DoesNotMatch("^Cineworld ", cinema.Name);
		}
	}
}
